# Generated by Django 4.2.7 on 2025-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='organization',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
