# Generated by Django 5.2.6 on 2025-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedsongs',
            name='bible_verse',
            field=models.TextField(),
        ),
    ]
