# Generated by Django 5.2.6 on 2025-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_generatedvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedsongsdata',
            name='audio_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
