# Generated by Django 5.2.6 on 2025-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_generatedsongsdata_audio_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
