# Generated by Django 5.2.6 on 2025-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_generatedvideo_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedvideo',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('queued', 'Queued')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedvideo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
