# Generated by Django 5.2.6 on 2026-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_generatedvideo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsongs',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedsongs',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedsongs',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
