# Generated by Django 4.2.7 on 2025-08-21 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.verse'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'testament')},
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('chapter', 'verse_number', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='readingplanday',
            unique_together={('reading_plan', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'verse')},
        ),
    ]
