# Generated by Django 4.2.7 on 2025-08-28 14:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleversion',
            name='bible_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=datetime.datetime(2025, 8, 28, 14, 33, 7, 604942, tzinfo=datetime.timezone.utc), max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='testament',
            field=models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=20),
        ),
    ]
