# Generated by Django 4.2.7 on 2025-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_bibleversion_bible_id_book_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
