# Generated by Django 4.2.7 on 2025-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0005_alter_bibleversion_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_number',
            field=models.CharField(max_length=10),
        ),
    ]
