# Generated by Django 4.2.7 on 2025-08-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0006_alter_chapter_chapter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bible_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
